<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Login\" />
    <Folder Include="Features\Auth\Logout\" />
    <Folder Include="Features\Auth\RefreshToken\" />
    <Folder Include="Features\Dashboard\Overview\" />
    <Folder Include="Features\MenuItem\List\" />
    <Folder Include="Features\Project\Delete\" />
    <Folder Include="Features\Project\List\" />
    <Folder Include="Features\Project\AssignMember\" />
    <Folder Include="Features\Project\Update\" />
    <Folder Include="Features\Task\Create\" />
    <Folder Include="Features\Task\Delete\" />
    <Folder Include="Features\Task\Get\" />
    <Folder Include="Features\Task\List\" />
    <Folder Include="Features\Task\Assign\" />
    <Folder Include="Features\Task\Update\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
      <PackageReference Include="MediatR" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
