FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY Directory.Build.props Directory.Packages.props DatavancedBD.AspNetCore.SmartTaskManagementSystem.slnx ./
COPY Admin/Admin.csproj Admin/
COPY Application/Application.csproj Application/
COPY Domain/Domain.csproj Domain/
COPY Infrastructure/Infrastructure.csproj Infrastructure/
COPY Shared/Shared.csproj Shared/
RUN dotnet restore Admin/Admin.csproj
COPY . .
RUN dotnet publish Admin/Admin.csproj --configuration Release --no-restore --output /out --no-self-contained

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /out .
USER $APP_UID
ENTRYPOINT ["dotnet", "Admin.dll"]
