environment: dev

ingress:
  host: stms-dev.example.com
  tlsSecretName: stms-dev-tls

api:
  replicas: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 3
  corsOrigins:
    - https://stms-dev.example.com

frontend:
  replicas: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 3

admin:
  migrationEnabled: false
